#!/bin/bash
### DO NOT EDIT THIS FILE ###
app_build_root=`pwd`
echo ${app_build_root}

#INIT_TARGET_PRODUCT=$1
#FINAL_TARGET_PRODUCT=$1
INIT_TARGET_PRODUCT=NX611J
FINAL_TARGET_PRODUCT=NX611J

KERNEL_PERF_DEFCONFIG=perf

echo -e "\033[01;32mINIT_TARGET_PRODUCT=${INIT_TARGET_PRODUCT}\033[0m"
echo -e "\033[01;32mFINAL_TARGET_PRODUCT=${FINAL_TARGET_PRODUCT}\033[0m"
################################################################################################

KERNEL_MODULES_OUT=${app_build_root}/out/target/product/${FINAL_TARGET_PRODUCT}/system/lib/modules
function mv-modules()
{
	mdpath=`find ${KERNEL_MODULES_OUT} -type f -name modules.dep`
	if [ "$mdpath" != "" ];then
		mpath=`dirname $mdpath`
		echo mpath=$mpath
		ko=`find $mpath/kernel -type f -name *.ko`
		for i in $ko
		do
			mv $i ${KERNEL_MODULES_OUT}/
		done
	fi
}

function clean-module-folder()
{
	mdpath=`find ${KERNEL_MODULES_OUT} -type f -name modules.dep`
	if [ "$mdpath" != "" ];then
		mpath=`dirname $mdpath`
		rm -rf $mpath
	fi
}

################################################################################################
export TARGET_KERNEL_APPEND_DTB=true

export TARGET_PRODUCT=NX611J
#由于kernel/script/Makefile.lib中设计TARGET_PRODUCT环境变量，因此需要设置export TARGET_PRODUCT=NX611J
#nubia: Set nubia overwrite dtsi file
#dtc_cpp_flags += -DNUBIA_OVERWRITE_DTSI_FILE=\"../nubia/$(TARGET_PRODUCT)/head.dtsi\"


#导出环境变量ZTEMT_DTS_NAME，并指定TARGET_KERNEL_APPEND_DTB到kernel后面
export ZTEMT_DTS_NAME="sdm636-mtp-${FINAL_TARGET_PRODUCT}.dtb sdm660-mtp-${FINAL_TARGET_PRODUCT}.dtb"
#echo -e "\033[01;32mZTEMT_DTS_NAME = ${ZTEMT_DTS_NAME}\033[0m"

if [ "${KERNEL_PERF_DEFCONFIG}" == "perf" ]
then
	KERNEL_DEFCONFIG=sdm660-perf-${FINAL_TARGET_PRODUCT}_defconfig
else
	KERNEL_DEFCONFIG=sdm660-${FINAL_TARGET_PRODUCT}_defconfig
fi
echo -e "\033[01;32mKERNEL_DEFCONFIG = ${KERNEL_DEFCONFIG}\033[0m"
################################################################################################


echo -e "\033[01;32m======================config build kernel environment value============================\033[0m"
export  PATH=${app_build_root}/prebuilts/gcc/linux-x86/aarch64/aarch64-linux-android-4.9/bin:${app_build_root}/prebuilts/gcc/linux-x86/arm/arm-linux-androideabi-4.9/bin:$PATH
export
echo -e "\033[01;32m=======================================================================================\033[0m"


echo -e "\033[01;32mdelete Image.gz-dtb...\033[0m"
rm -rf out/target/product/${FINAL_TARGET_PRODUCT}/obj/KERNEL_OBJ/arch/arm64/boot

echo -e "\033[01;32mBuilding .config...\033[0m"
make -C kernel/msm-4.4 O=../../out/target/product/${FINAL_TARGET_PRODUCT}/obj/kernel/msm-4.4 ARCH=arm64 CROSS_COMPILE=aarch64-linux-android- ${KERNEL_DEFCONFIG}


################################################################################################
echo -e "\033[01;32mBuilding kernel...\033[0m"
make -C kernel/msm-4.4 O=../../out/target/product/${FINAL_TARGET_PRODUCT}/obj/kernel/msm-4.4 ARCH=arm64 CROSS_COMPILE=aarch64-linux-android- KCFLAGS=-mno-android  -j`grep processor /proc/cpuinfo |wc -l`
RET_VAL=$?
make -C kernel/msm-4.4 O=../../out/target/product/${FINAL_TARGET_PRODUCT}/obj/kernel/msm-4.4 ARCH=arm64 CROSS_COMPILE=aarch64-linux-android- KCFLAGS=-mno-android modules
make -C kernel/msm-4.4 O=../../out/target/product/${FINAL_TARGET_PRODUCT}/obj/kernel/msm-4.4 INSTALL_MOD_PATH=../../../system INSTALL_MOD_STRIP=1 ARCH=arm64 CROSS_COMPILE=aarch64-linux-android- modules_install

echo -e "\033[01;32mmv-modules clean-module-folder...\033[0m"
mv-modules
clean-module-folder

if [ $RET_VAL -gt 0 ]
then
	echo -e "\033[01;32m***********************************************************\033[0m"
	echo -e "\033[01;31m         Build error!!! Please see build log above         \033[0m"
	echo -e "\033[01;32m***********************************************************\033[0m"
	exit $RET_VAL
fi
################################################################################################


echo -e "\033[01;32mcp -rf Image.gz-dtb kernel...\033[0m"
cp -rf out/target/product/${FINAL_TARGET_PRODUCT}/obj/kernel/msm-4.4/arch/arm64/boot/Image.gz-dtb out/target/product/${FINAL_TARGET_PRODUCT}/kernel


echo -e "\033[01;32mmkbootfs ramdisk.img...\033[0m"
out/host/linux-x86/bin/mkbootfs -d out/target/product/${FINAL_TARGET_PRODUCT}/system out/target/product/${FINAL_TARGET_PRODUCT}/root | out/host/linux-x86/bin/minigzip > out/target/product/${FINAL_TARGET_PRODUCT}/ramdisk.img


################################################################################################
echo -e "\033[01;32mmkbootimg boot.img...\033[0m"
#BOARD_KERNEL_CMDLINE=`grep "BOARD_KERNEL_CMDLINE :="  device/zte/common/BoardConfig.mk`
#if [ "$BOARD_KERNEL_CMDLINE" == "" ];then
#   	echo Error:BOARD_KERNEL_CMDLINE not found
#   	exit 1
#fi
#KERNEL_CMDLINE=`echo ${BOARD_KERNEL_CMDLINE#*:=}`
#echo KERNEL_CMDLINE=$KERNEL_CMDLINE
out/host/linux-x86/bin/mkbootimg --kernel out/target/product/${FINAL_TARGET_PRODUCT}/kernel --ramdisk out/target/product/${FINAL_TARGET_PRODUCT}/ramdisk.img --base 0x00000000 --pagesize 4096 --cmdline "console=ttyMSM0,115200,n8 androidboot.console=ttyMSM0 earlycon=msm_serial_dm,0xc1700000000 androidboot.hardware=qcom user_debug=31 msm_rtb.filter=0x237 ehci-hcd.park=3 lpm_levels.sleep_disabled=1 sched_enable_hmp=1 sched_enable_power_aware=1 service_locator.enable=1 swiotlb=1 androidboot.configfs=true androidboot.usbcontroller=a800000.dwc3 buildvariant=userdebug" --os_version 8.1.0 --os_patch_level 2018-02-05 --output out/target/product/${FINAL_TARGET_PRODUCT}/boot.img

#out/host/linux-x86/bin/mkbootimg  --kernel out/target/product/${FINAL_TARGET_PRODUCT}/kernel --ramdisk out/target/product/${FINAL_TARGET_PRODUCT}/ramdisk.img --cmdline "$KERNEL_CMDLINE" --base 0x00000000 --pagesize 4096  --output out/target/product/${FINAL_TARGET_PRODUCT}/boot.img
################################################################################################


echo -e "\033[01;32mboot_signer boot.img...\033[0m"
out/host/linux-x86/bin/boot_signer /boot out/target/product/${FINAL_TARGET_PRODUCT}/boot.img build/target/product/security/verity.pk8 build/target/product/security/verity.x509.pem out/target/product/${FINAL_TARGET_PRODUCT}/boot.img


echo "[01;32m==================================================================[0m"
echo "Now, the boot.img images are in dir:"
echo -e "\033[01;32m${app_build_root}/out/target/product/${FINAL_TARGET_PRODUCT}/boot.img\033[0m"
echo "[01;32m==================================================================[0m"


echo "=============================================="
echo          Build finished at `date`.
echo "=============================================="


### DO NOT EDIT THIS FILE ###
